### ISSUE TITLE
Usage of ha_ostrom

### ISSUE THREAD

**Issue by AditaNi** [melmager/ha_ostrom#2]
Hi,

Please help me to configure my homeassistant in order to see the data.

Regards
Adrian

**Comment by melmager** [comment]
you need apexcharts-card 
https://github.com/RomRider/apexcharts-card
after installation via HACS 
add an apex card in lovelance

Code for Card:

type: custom:apexcharts-card
graph_span: 36h
span:
  start: hour
  offset: +0h
now:
  show: true
  label: Jetzt
all_series_config:
  unit: cent
header:
  show: true
  show_states: true
  colorize_states: true
  title: Preis Forecast
series:
  - entity: ostrom.price
    data_generator: |
      return entity.attributes.data.map((start, index) => {
        return [new Date(start["date"]).getTime(), (entity.attributes.data[index]["price"])];
      });
    extend_to: false

and get a Grafik for Price Data

**Comment by melmager** [comment]
for Past Data: (100 days)

```
type: custom:apexcharts-card
graph_span: 100d
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
update_interval: 1h
series:
  - entity: ostrom.price
    type: column
    show:
      datalabels: false
  - entity: ostrom.price
    attribute: average

```
